In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [2]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     -------------------------------------- 294.9/294.9 KB 1.7 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.2 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.4)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.53.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ravi daliparthy\appdata\roaming\python\python39\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: cycler>=0.10 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: packaging>=20.0 in c:\users\ravi daliparthy\appdata\roaming\python\python39\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.4.4)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\ravi daliparthy\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: zipp>=3.1.0 in c:\users\ravi daliparthy\appdata\roaming\python\python39\site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.19.2)
Requirement already satisfied: six>=1.5 in c:\users\ravi daliparthy\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 24.2 is available.
You should consider upgrading via the 'c:\Users\Ravi Daliparthy\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [12]:
data = pd.read_csv("housing.csv")
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [14]:
data.isna().sum()/len(data)*100

longitude             0.000000
latitude              0.000000
housing_median_age    0.000000
total_rooms           0.000000
total_bedrooms        1.002907
population            0.000000
households            0.000000
median_income         0.000000
median_house_value    0.000000
ocean_proximity       0.000000
dtype: float64

In [15]:
data.dropna(inplace=True)

In [16]:
data['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [17]:
data['ocean_proximity'].replace(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],[0,1,2,3,4],inplace=True)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  int64
dtypes: float64(9), int64(1)
memory usage: 1.7 MB

In [19]:
X = data.drop(columns=['median_house_value'])
y = data['median_house_value']

In [20]:
scaler = StandardScaler()
scaled_x = scaler.fit_transform(X)

In [21]:
scaled_x

array([[-1.32731375,  1.05171726,  0.98216331, ..., -0.97683327,
         2.34516291, -1.71481644],
       [-1.32232256,  1.04235526, -0.60621017, ...,  1.67037262,
         2.33263161, -1.71481644],
       [-1.33230494,  1.03767426,  1.85576873, ..., -0.84342665,
         1.78293943, -1.71481644],
       ...,
       [-0.82320322,  1.77727236, -0.92388486, ..., -0.17377773,
        -1.14317103,  0.62656975],
       [-0.87311515,  1.77727236, -0.84446619, ..., -0.39350628,
        -1.05513604,  0.62656975],
       [-0.83318561,  1.74918635, -1.00330353, ...,  0.07995643,
        -0.78060586,  0.62656975]])

In [22]:
X_train,X_test,y_train,y_test = train_test_split(scaled_x,y,test_size=0.2,random_state=0)

In [23]:
regr = DecisionTreeRegressor()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6387001901641618
44268.82211891363

In [24]:
regr = RandomForestRegressor()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.8127150847136972
32486.381624663565

In [25]:
regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6415883892836358
51201.82937014007

******************************************************

******************************************************

******************************************************

## Data normalization

When normalizing the data for Classification, then only normalize the input features (X)

When normalizing the data for Regression, then normalize the entire data including input features (X), output feature (y)

In [26]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,2
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,2
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,2
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,2
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,2

In [27]:
X = data.drop(columns=['median_house_value'])
y = pd.DataFrame(data['median_house_value'])

In [28]:
input_scaler = StandardScaler()
scaled_X = input_scaler.fit_transform(X)

output_scaler = StandardScaler()
scaled_y = output_scaler.fit_transform(y)

In [29]:
X_train,X_test,y_train,y_test = train_test_split(scaled_X,scaled_y,test_size=0.2,random_state=0)

In [30]:
regr = DecisionTreeRegressor()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6273298004024983
0.3869869232057074

In [31]:
regr = RandomForestRegressor()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8097512158599293
0.2838414691176389

In [32]:
regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6415883892836358
0.443563792916955

******************************************************

******************************************************

******************************************************

In [33]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,2
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,2
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,2
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,2
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,2

In [34]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

In [35]:
scaled_data

array([[-1.32731375,  1.05171726,  0.98216331, ...,  2.34516291,
         2.12881864, -1.71481644],
       [-1.32232256,  1.04235526, -0.60621017, ...,  2.33263161,
         1.31362603, -1.71481644],
       [-1.33230494,  1.03767426,  1.85576873, ...,  1.78293943,
         1.25818254, -1.71481644],
       ...,
       [-0.82320322,  1.77727236, -0.92388486, ..., -1.14317103,
        -0.99247676,  0.62656975],
       [-0.87311515,  1.77727236, -0.84446619, ..., -1.05513604,
        -1.05831591,  0.62656975],
       [-0.83318561,  1.74918635, -1.00330353, ..., -0.78060586,
        -1.01759959,  0.62656975]])

In [36]:
scaled_data = pd.DataFrame(scaled_data,columns = data.columns)
scaled_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-1.327314,1.051717,0.982163,-0.803813,-0.970325,-0.973320,-0.976833,2.345163,2.128819,-1.714816
1,-1.322323,1.042355,-0.606210,2.042130,1.348276,0.861339,1.670373,2.332632,1.313626,-1.714816
2,-1.332305,1.037674,1.855769,-0.535189,-0.825561,-0.819769,-0.843427,1.782939,1.258183,-1.714816
3,-1.337296,1.037674,1.855769,-0.623510,-0.718768,-0.765056,-0.733562,0.932970,1.164622,-1.714816
4,-1.337296,1.037674,1.855769,-0.461970,-0.611974,-0.758879,-0.628930,-0.013143,1.172418,-1.714816
...,...,...,...,...,...,...,...,...,...,...
20428,-0.758318,1.800677,-0.288535,-0.444580,-0.388895,-0.511787,-0.443207,-1.216727,-1.115492,0.626570
20429,-0.818212,1.805358,-0.844466,-0.887557,-0.920488,-0.943315,-1.008223,-0.692044,-1.124155,0.626570
20430,-0.823203,1.777272,-0.923885,-0.175042,-0.125472,-0.368826,-0.173778,-1.143171,-0.992477,0.626570
20431,-0.873115,1.777272,-0.844466,-0.355344,-0.305834,-0.603564,-0.393506,-1.055136,-1.058316,0.626570
20432,-0.833186,1.749186,-1.003304,0.067955,0.185416,-0.033487,0.079956,-0.780606,-1.017600,0.626570

In [37]:
X = scaled_data.drop(columns=['median_house_value'])
y = pd.DataFrame(scaled_data['median_house_value'])

In [38]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [39]:
regr = DecisionTreeRegressor()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6330374095004374
0.3855279577663228

In [40]:
regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6415883892836357
0.443563792916955

In [41]:
regr = RandomForestRegressor()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.809294025410599
0.28381298516294345

******************************************************

******************************************************

******************************************************

In [50]:
import pickle

with open("rf.pkl",'wb') as f:
    pickle.dump(regr,f)

with open("input_scaler.pkl",'wb') as f:
    pickle.dump(input_scaler,f)

with open("output_scaler.pkl",'wb') as f:
    pickle.dump(output_scaler,f)

In [51]:
with open("rf.pkl",'rb') as f:
    rf = pickle.load(f)

with open("input_scaler.pkl",'rb') as f:
    inscaler = pickle.load(f)

with open("output_scaler.pkl",'rb') as f:
    outscaler = pickle.load(f)

## Inference

In [44]:
input = [['-122.23','37.88','41.0','880.0','129.0','322.0','126.0','8.3252',1]]

scaledinput = inscaler.transform(input)
rf_pred = rf.predict(scaledinput)
rf_pred

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([2.10180865])

In [45]:
prediction = outscaler.inverse_transform([rf_pred])
prediction[0][0]

449482.1600000004

*******************************

In [46]:
input = [['-5622.23','9.88','418.0','2580.0','929.0','122.0','1296.0','18.3252',3]]

scaled_input = input_scaler.transform(input)
rf_pred = rf.predict(scaled_input)
rf_pred

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([2.43083737])

In [47]:
prediction = output_scaler.inverse_transform([rf_pred])
prediction[0][0]

487462.88

## Prediction

In [48]:
import pickle

def Predict_House_Pricing(input):

    clf = pickle.load(open("rf.pkl","rb"))
    i_scaler = pickle.load(open("input_scaler.pkl","rb"))
    o_scaler = pickle.load(open("output_scaler.pkl","rb"))

    scaled_input = i_scaler.transform([input])
    prediction = clf.predict(scaled_input)

    transformed_prediction = o_scaler.inverse_transform([prediction])

    return transformed_prediction[0][0]

Predict_House_Pricing(['-5622.23','9.88','418.0','2580.0','929.0','122.0','1296.0','18.3252',3])

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

487462.88

In [49]:
Predict_House_Pricing(['-122.23','37.88','41.0','880.0','129.0','322.0','126.0','8.3252',1])

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

449482.1600000004